@host=http://express-node-app:3000

###
GET {{host}}/api/tests HTTP/1.1

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200
    );
  });
}}
###

POST {{host}}/api/tests HTTP/1.1

{{
  test.status(201);
}}
###

PUT {{host}}/api/tests HTTP/1.1

{{
  test.status(200);
}}
###

DELETE {{host}}/api/tests HTTP/1.1

{{
  test.status(200);
}}
###
